# Generated by Django 3.0.5 on 2020-04-08 21:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('serviceDate', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('pruningHours', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('haulHours', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('primaryPlants', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
